### ISSUE TITLE
Use weak instead unowned in tutorial

### ISSUE THREAD

**Issue by Austinate** [collinhundley/APTargets#3]
Hi! 
As we're trying to have less crashes and make target-action safer — i think it's better to use weak because unowned can lead to crash in runtime if object will be deallocated.

If you agree — i can create a PR with this change.

**Comment by collinhundley** [comment]
@Austinate  You're right that `weak` can be safer than `unowned` if there is a possibility of the object being deallocated, however it also adds some additional overhead.

In the common case of a `UIButton` being the child of a `UIViewController`, using `unowned` is preferred.  (If you think about it, it won't be possible for the button to be selected if the view controller has already been dismissed). This is the scenario outlined in the example, which is why I chose to use `unowned`.

It's probably a good idea to add a note mentioning that `weak` might be more appropriate for some situations, though.
